### PR TITLE
Fixing issues, optimizing code.

### PR DESCRIPTION
**Pull request by DuncanCarr**
Organization is a big thing, as a developer, and you must learn to effectively organize your code for ease of access,
    especially, if you plan on sharing it on a platform such as GitHub, or GitLab, for other developers to use in their
    projects. I added more packages to make things more identifiable.

    You also make some very basic mistakes, which I will correct in my rendition of this plugin, and there are some
    small ways you could improve your code, as well.

    I will not explain everything, as you seem pretty well versed with at least standard Java principles, so you should
    be able to understand everything, but let me know if that is not correct, and I will elaborate.

### CODE REVIEW

**Comment by DuncanCarr** [comment]
I ask that if you do end up merging and using this version of the plugin, that you add me as an author on your spigot page.

**Review by 16amattice — COMMENTED** [review]
I decided to take a look at this and I do see some areas where optimization could happen. I am working on getting better and I thank you for the suggestion. I will be changing to the UUID, but I will be keeping my files the same because I do not want to change things around too much as I had them working already. Thanks anyways :)

**Comment by KingAlterIV** [comment]
Why is the code from the update and this PR the same, despite it showing no credits to this PR and being closed with this statement, 
> I will be keeping my files the same because I do not want to change things around too much as I had them working already.

**Comment by 16amattice** [comment]
I appreciated the code that he submitted and did use some if it for my code. Not all of his changes were implemented. I put the code on github for people to look at. I have this plugin licensed and am not looking for reviews on how to make my code better, just for myself and people to look at. I would appreciate in the future if people would talk to me first before rewriting a plugin I make and then leaving a low review because of it. I will not be accepted future pull requests, but am always open to suggestions to my plugins. Thanks

**Comment by KingAlterIV** [comment]
The low review was before version 1.1.

From what I see looking at the PR and this, it's all implemented, and with class names changed and comments removed.
**Left = This PR**
**Right = Chat Reverser v1.1**
Image 1
Image 2
Image 3

**Comment by 16amattice** [comment]
I dont know if this is the same guy or not, but I am not accepting more changes in code. Thanks for your insight.

**Comment by 16amattice** [comment]
I am a new developer and I know I have made a lot of mistakes, with this PR, and with the code I originally wrote in general. No matter how good I thought my code was I should not have stole someone else work and made it my own. For that you have my sincerest apologies and I hope this helps fix things and I hope it makes me a better developer in the future. I have given credit to the user who made this PR and will continue to do so in the future. I will not accept this PR because of now conflicting code, but I will state I used his code in the current version. Will now be closing this thread. Thanks all!

**Pull request closed without merging**
